language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "2.7"
  - "2.6"

env:
    - LXML=true
    - LXML=false
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
# install: PLEASE CHANGE ME
install:
    - pip install coveralls --use-mirrors
    - if $LXML == true; then pip install --use-mirrors lxml; fi

# command to run tests, e.g. python setup.py test

script:
    coverage run --source=fastkml setup.py test

after_success:
    coveralls

notifications:
  email:
    - christian.ledermann@gmail.com
