language: python
python:
- '3.2'
- '3.3'
- '3.4'
- '2.7'
- '2.6'
env:
- LXML=true
- LXML=false
install:
- pip install -r requirements.txt
- if $LXML == true; then pip install lxml; fi
- if [[ $TRAVIS_PYTHON_VERSION == 2.6 ]]; then pip install unittest2; fi
script:
- coverage run --source=fastkml setup.py test
- if [[ $TRAVIS_PYTHON_VERSION != 3.2 ]]; then cd docs && make html; fi
after_success: coveralls
notifications:
  email:
  - christian.ledermann@gmail.com
  - IanLee1521@gmail.com
deploy:
 provider: pypi
  user: "Christian.Ledermann"
  password:
    secure: Ri6RrdNePDkWWuOgtmbWHQWsZHerEVdI570AuCOWJVxHHyFGTdcsAXfklOwj5W3iE/2URjvtEb47UIorWvwmhI2TvGRkFSt8NS4gFEVXakquxwslYsK6CPFjo/PT2BoCiB93WJJmNWlwyERrjThaJYomEDlvb8IF+Qrru3wKm0Y=
  distributions: "sdist bdist_wheel"
  on:
    tags: true
