language: python
python:
- '3.2'
- '3.3'
- '3.4'
- '2.7'
- '2.6'
env:
- LXML=true
- LXML=false
before_install:
- pip install codecov
install:
- pip install -r requirements.txt
- if $LXML == true; then pip install lxml; fi
- if [[ $TRAVIS_PYTHON_VERSION == 2.6 ]]; then pip install unittest2; fi
script:
- coverage run --source=fastkml setup.py test
- if [[ $TRAVIS_PYTHON_VERSION != 3.2 ]]; then cd docs && make html; fi
after_success:
- codecov
- coveralls
notifications:
  email:
  - christian.ledermann@gmail.com
  - IanLee1521@gmail.com
deploy:
  provider: pypi
  user: Christian.Ledermann
  password:
    secure: MhOkMil0/EsZRS1FB6xYiFfjbFjafYuBE/bKMnsHZqtoVU/CH0UCfjIJpDyRzYeTliub84r7hwHzTwnDzxijWIdy8T4tcuVja0Iu8ItGc4VopYKyUjUgxUT9PWk0in5C/gtwEQb2VYOhrQA9F3XRZ6RfHvUAJJYhdV2GM6ehm+0=
  on:
    tags: true
    repo: cleder/fastkml
