language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "2.7"
  - "2.6"
  - "pypy"
#  - "pypy3" this has problems with lxml so we leave it out for now, works fine
# without lxml

env:
    - LXML=true
    - LXML=false

# command to install dependencies, e.g. pip install -r requirements.txt
install:
    - pip install -r requirements/test.txt
    - if $LXML == true; then pip install lxml; fi
    - if [[ $TRAVIS_PYTHON_VERSION == 2.6 ]]; then pip install unittest2; fi

# command to run tests, e.g. python setup.py test
script:
    - pep8 --exclude test_main.py fastkml
    - coverage run --source=fastkml setup.py test

after_success:
    coveralls

notifications:
  email:
    - christian.ledermann@gmail.com
    - IanLee1521@gmail.com
